apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
  labels:
    app: products 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
        - name: userhandle
          image: siddharthtewari/cc_products
          ports:
          - containerPort: 5002
          imagePullPolicy: Always

--- 
apiVersion: v1
kind: Service
metadata:
  name: products-service
spec:
  selector:
    app: products
  ports:
  - port: 5000
    targetPort: 5002 
  type: LoadBalancer
